I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\Ori\Desktop\Buscando a la Luna/game/submenu_animales.rpy.
ScriptError: Name u'tutorial_rollback' is defined twice, at game/submenu_animales.rpy:31 and game/submenu_telescopio.rpy:31.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Ori\Desktop\Renpy\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Ori\Desktop\Renpy\renpy\main.py", line 354, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\Ori\Desktop\Renpy\renpy\script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Ori\Desktop\Renpy\renpy\script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Ori\Desktop\Renpy\renpy\script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'tutorial_rollback' is defined twice, at game/submenu_animales.rpy:31 and game/submenu_telescopio.rpy:31.

Windows-7-6.1.7600
Ren'Py 6.99.10.1227
 
